import React from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export function CalculatorField({ label, value, onChange, prefix, suffix, min = 0, max }: { label: string; value: string; onChange: (value: string) => void; prefix?: string; suffix?: string; min?: number; max?: number }) {
  const parsed = value === "" ? null : Number(value);
  const invalid = parsed !== null && (!Number.isFinite(parsed) || parsed < min || (max !== undefined && parsed > max));
  const message = parsed !== null && !Number.isFinite(parsed) ? "Please enter a finite number." : max !== undefined && parsed !== null && parsed > max ? `Please enter a value between ${min} and ${max}.` : min > 0 ? `Please enter a value of ${min} or more.` : "Please enter a value of 0 or more.";
  return <div className="space-y-2"><Label className="text-sm font-semibold text-slate-700">{label}</Label><div className="relative">{prefix && <span className="pointer-events-none absolute left-3 top-2.5 text-slate-400" aria-hidden="true">{prefix}</span>}<Input aria-label={label} aria-invalid={invalid} aria-describedby={invalid ? `${label.replace(/\W+/g, "-")}-error` : undefined} type="number" min={min} max={max} inputMode="decimal" value={value} onChange={e => onChange(e.target.value)} className={`h-11 border-slate-200 bg-white ${prefix ? "pl-8" : ""} ${suffix ? "pr-10" : ""} ${invalid ? "border-red-400" : ""}`} />{suffix && <span className="pointer-events-none absolute right-3 top-2.5 text-slate-400" aria-hidden="true">{suffix}</span>}</div>{invalid && <p id={`${label.replace(/\W+/g, "-")}-error`} role="alert" className="text-xs font-medium text-red-600">{message}</p>}</div>;
}
export function ResultCard({ label, value, tone }: { label: string; value: string; tone?: "primary" | "positive" | "muted" }) { return <div className="rounded-xl border border-white/10 bg-white/[0.06] p-4"><p className="text-xs text-blue-200">{label}</p><p className={`mt-1 text-lg font-bold ${tone === "positive" ? "text-emerald-300" : tone === "muted" ? "text-blue-100" : "text-white"}`}>{value}</p></div>; }
export function FormulaSection({ formula }: { formula: string }) { return <CardLike><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Formula</p><p className="mt-4 font-mono text-sm leading-6 text-slate-700">{formula}</p><p className="mt-4 text-xs leading-5 text-slate-500">Rates, taxes, fees, returns, and provider policies vary. Verify assumptions before acting.</p></CardLike>; }
export function FAQSection({ title, items }: { title?: string; items: [string, string][] }) { return <section className="mt-12"><h2 className="text-2xl font-bold text-slate-950">{title || "Frequently asked questions"}</h2><div className="mt-5 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white">{items.map(([q,a]) => <details key={q} className="group p-5"><summary className="cursor-pointer list-none pr-8 font-bold text-slate-800 marker:hidden">{q}<span aria-hidden="true" className="float-right text-blue-600 transition group-open:rotate-45">+</span></summary><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{a}</p></details>)}</div></section>; }
export function TimeSeriesBars({ data }: { data: { label: string; value: number }[] }) { const safe = data.filter(point => Number.isFinite(point.value)); const max = Math.max(...safe.map(x => x.value), 1); return <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5" aria-label="Projected balance chart"><div className="flex h-36 items-end gap-2">{safe.map(point => <div key={point.label} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><div role="img" aria-label={`${point.label}: $${point.value.toFixed(0)}`} className="w-full rounded-t-md bg-emerald-400 transition group-hover:bg-blue-500" style={{ height: `${Math.max(8, point.value / max * 100)}%` }} /><span className="text-[10px] text-slate-400">{point.label}</span></div>)}</div><div className="mt-4 min-w-0 overflow-x-auto"><table className="w-full min-w-0 text-left text-xs text-slate-500"><caption className="sr-only">Projected balances over time</caption><thead><tr><th className="py-1">Year</th><th className="py-1 text-right">Projected balance</th></tr></thead><tbody>{safe.map(point => <tr key={`table-${point.label}`} className="border-t border-slate-100"><td className="py-1">{point.label}</td><td className="py-1 text-right">${point.value.toFixed(0)}</td></tr>)}</tbody></table></div></div>; }
function CardLike({ children }: { children: React.ReactNode }) { return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-6 sm:p-8">{children}</div>; }
