import React from "react";
import { Link } from "wouter";
import { ArrowRight, BookOpen, Calculator, ChevronRight, ExternalLink } from "lucide-react";
import { FAQSection, FormulaSection } from "@/components/CalculatorParts";
import type { CalculatorContent, CategoryContent, BlogArticle } from "@shared/seoContent";
import { calculatorContent, categoryContent, publishedCategoryOrder } from "@shared/seoContent";
import type { CalculatorKind } from "@shared/calculators";

const paths: Record<CalculatorKind, string> = { loan: "/loan-calculator", mortgage: "/mortgage-calculator", personalLoan: "/personal-loan-calculator", salary: "/salary-calculator", takeHome: "/take-home-pay-calculator", compound: "/compound-interest-calculator", investment: "/investment-calculator", roi: "/roi-calculator", profitMargin: "/profit-margin-calculator", currency: "/currency-converter", savings: "/savings-calculator", simpleInterest: "/simple-interest-calculator", markup: "/markup-calculator", discount: "/discount-calculator", salesTax: "/sales-tax-calculator" };
const labels: Record<CalculatorKind, string> = { loan: "Loan Calculator", mortgage: "Mortgage Calculator", personalLoan: "Personal Loan Calculator", salary: "Salary Calculator", takeHome: "Take-Home Pay Calculator", compound: "Compound Interest Calculator", investment: "Investment Calculator", roi: "ROI Calculator", profitMargin: "Profit Margin Calculator", currency: "Currency Converter", savings: "Savings Calculator", simpleInterest: "Simple Interest Calculator", markup: "Markup Calculator", discount: "Discount Calculator", salesTax: "Sales Tax Calculator" };

export function Breadcrumbs({ category, current }: { category: string; current: string }) {
  const categoryHref = `/${category}`;
  const items = [{ label: "Home", href: "/" }, { label: category[0].toUpperCase() + category.slice(1), href: categoryHref }, { label: current }];
  const schema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.label, ...(item.href ? { item: `${window.location.origin}${item.href}` } : {}) })) };
  return <><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-1 text-sm font-semibold text-slate-400">{items.map((item, index) => <span key={item.label} className="flex items-center gap-1">{index > 0 && <ChevronRight className="h-4 w-4" aria-hidden="true" />}{item.href ? <Link href={item.href} className="hover:text-blue-700">{item.label}</Link> : <span aria-current="page" className="text-slate-500">{item.label}</span>}</span>)}</nav><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /></>;
}

export function CalculatorEducation({ content }: { content: CalculatorContent }) {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: content.faq.map(item => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) };
  return <div className="mt-16 max-w-3xl space-y-12"><section><h2 className="text-2xl font-bold text-slate-950">How to use this calculator</h2><p className="mt-4 leading-8 text-slate-600">{content.howToUse}</p></section><section><h2 className="text-2xl font-bold text-slate-950">How the calculation works</h2><p className="mt-4 leading-8 text-slate-600">{content.howItWorks}</p></section><FormulaSection formula={content.formula} /><section><h2 className="text-2xl font-bold text-slate-950">What the variables mean</h2><ul className="mt-4 space-y-3 text-slate-600">{content.variableDefinitions.map(item => <li key={item} className="flex gap-3 leading-7"><span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />{item}</li>)}</ul></section><section className="rounded-2xl border border-emerald-100 bg-emerald-50/70 p-6"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Worked example</p><p className="mt-3 leading-7 text-emerald-950">{content.example}</p></section><section><h2 className="text-2xl font-bold text-slate-950">Important assumptions</h2><ul className="mt-4 space-y-3 text-slate-600">{content.assumptions.map(item => <li key={item} className="flex gap-3 leading-7"><span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-blue-600" />{item}</li>)}</ul></section><section><h2 className="text-2xl font-bold text-slate-950">Common mistakes to avoid</h2><ul className="mt-4 space-y-3 text-slate-600">{content.commonMistakes.map(item => <li key={item} className="flex gap-3 leading-7"><span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-500" />{item}</li>)}</ul></section><FAQSection items={content.faq.map(item => [item.question, item.answer])} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /></div>; }

export function RelatedLinks({ kinds }: { kinds: CalculatorKind[] }) { return <section className="mt-16"><div className="flex items-end justify-between"><div><p className="eyebrow">Continue exploring</p><h2 className="mt-2 text-3xl font-bold text-slate-950">Related calculators</h2></div><Link href="/calculators" className="hidden items-center gap-2 text-sm font-bold text-blue-700 sm:flex">View all <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{kinds.map(kind => <Link key={kind} href={paths[kind]} className="group rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-lg"><p className="font-bold text-slate-900">{labels[kind]}</p><p className="mt-2 text-sm leading-6 text-slate-500">{calculatorContent[kind].intro}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue-700">Open calculator <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></section>; }

export function CategoryIndex() { return <main className="container py-12 sm:py-16"><Breadcrumbs category="categories" current="All categories" /><div className="mt-8 max-w-3xl"><p className="eyebrow">MoneyCalci structure</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-slate-950 sm:text-6xl">Browse by topic</h1><p className="mt-5 text-lg leading-8 text-slate-600">Move through focused hubs instead of a long, unrelated directory. Each hub explains its purpose and links to the calculators that belong there.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{publishedCategoryOrder.map(slug => { const content = categoryContent[slug] as CategoryContent; return <Link key={content.slug} href={`/${content.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-lg"><h2 className="text-xl font-bold text-slate-950">{content.name}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{content.intro}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue-700">Explore hub <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>; })}</div></main>; }

export function CategoryHub({ content }: { content: CategoryContent }) { return <main className="container py-12 sm:py-16"><Breadcrumbs category="categories" current={content.name} /><div className="mt-8 max-w-3xl"><p className="eyebrow">MoneyCalci category</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-slate-950 sm:text-6xl">{content.name}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{content.intro}</p></div><section className="mt-10"><p className="max-w-3xl leading-8 text-slate-600">{content.body}</p><div className="mt-8 grid gap-4 md:grid-cols-2">{content.calculatorKinds.map(kind => <Link key={kind} href={paths[kind]} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-lg"><div className="flex items-start justify-between gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><Calculator className="h-5 w-5" /></div><ArrowRight className="h-5 w-5 text-slate-300 transition group-hover:translate-x-1 group-hover:text-blue-700" /></div><h2 className="mt-5 text-xl font-bold text-slate-950">{labels[kind]}</h2><p className="mt-2 leading-7 text-slate-500">{calculatorContent[kind].intro}</p></Link>)}</div>{content.calculatorKinds.length === 0 && <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-6 text-slate-600">This hub is intentionally reserved for a useful, verified calculator rather than a thin placeholder page.</div>}</section><FAQSection items={content.faq.map(item => [item.question, item.answer])} /><div className="mt-12 rounded-2xl border border-slate-200 bg-slate-50 p-6 text-sm leading-6 text-slate-600"><strong className="text-slate-900">MoneyCalci methodology:</strong> Each published tool is designed to answer a specific calculation intent, show assumptions, and link to the next useful comparison. We do not publish invented benchmarks, fake reviews, or unsupported financial claims.</div></main>; }

export function BlogIndex({ articles }: { articles: BlogArticle[] }) { return <main className="container py-12 sm:py-16"><Breadcrumbs category="blog" current="Guides" /><div className="mt-8 max-w-3xl"><p className="eyebrow">MoneyCalci guides</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-slate-950 sm:text-6xl">Learn the numbers behind the tools.</h1><p className="mt-5 text-lg leading-8 text-slate-600">Focused explanations that connect a real money question to a useful calculator—without filler or mass-produced pages.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{articles.map(article => <Link key={article.slug} href={`/blog/${article.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-lg"><BookOpen className="h-5 w-5 text-blue-700" /><h2 className="mt-5 text-xl font-bold text-slate-950">{article.title}</h2><p className="mt-2 leading-7 text-slate-500">{article.description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-blue-700">Read guide <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></main>; }

export function BlogArticlePage({ article }: { article: BlogArticle }) { const content = calculatorContent[article.calculatorKind]; const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, mainEntityOfPage: `${window.location.origin}/blog/${article.slug}`, dateModified: content.lastUpdated, about: content.seoTitle }; return <main className="container py-12 sm:py-16"><Breadcrumbs category="blog" current={article.title} /><article className="mt-8 max-w-3xl"><p className="eyebrow">MoneyCalci guide</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-slate-950 sm:text-6xl">{article.title}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{article.intro}</p><p className="mt-3 text-xs font-semibold uppercase tracking-widest text-slate-400">Updated {content.lastUpdated}</p>{article.sections.map(section => <section key={section.heading} className="mt-10"><h2 className="text-2xl font-bold text-slate-950">{section.heading}</h2><p className="mt-4 leading-8 text-slate-600">{section.body}</p></section>)}<div className="mt-10 rounded-2xl bg-[#10233f] p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Put it into practice</p><h2 className="mt-3 text-2xl font-bold">{content.seoTitle.replace(" — ", ": ")}</h2><p className="mt-3 leading-7 text-blue-100">{content.intro}</p><Link href={paths[article.calculatorKind]} className="mt-6 inline-flex items-center gap-2 font-bold text-emerald-300 hover:text-emerald-200">Open calculator <ExternalLink className="h-4 w-4" /></Link></div></article><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /></main>; }

export function FutureAdSlot({ label = "Future relevant placement" }: { label?: string }) { return <div aria-label={label} className="mt-10 hidden rounded-xl border border-dashed border-slate-200 bg-slate-50 p-4 text-center text-xs text-slate-400">Reserved for a clearly labeled, relevant placement. MoneyCalci remains useful without ads.</div>; }
export function FutureAffiliateSlot({ label = "Future relevant recommendation" }: { label?: string }) { return <div aria-label={label} className="mt-6 hidden rounded-xl border border-dashed border-slate-200 bg-white p-4 text-center text-xs text-slate-400">Reserved for a relevant recommendation. No partnership or affiliate relationship is active.</div>; }
